# Read the Docs build configuration
# https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - plotting
