#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/andrew/Apps/NEURON/build/7.0"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/andrew/Apps/NEURON/build/7.0/i686/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/andrew/dev/pyNN_trunk/src/hoc/i686/.libs/libnrnmech.so" "$@"
